package com.example.server.enums;

public enum CategoryIcon {
    RECEIPT, PLANE, TAG, PET, MONITOR, POT, SHOPPING_CART, BRUSH, WASHING_MACHINE,
    TENT, CONTROLLER, CAR, FIRST_AID, BOOK, TSHIRT, SHOE, FOOD, RESTAURANT, CAFE,
    HOUSE, THERAPY, EDUCATION, GIFT, CLEANING, FAMILY, SPORTS, TRANSPORT, SALARY,
    LOAN, TRADE, OTHERS
}
